# Generated by Django 4.2 on 2024-10-25 14:41

from django.db import migrations, models
import django.db.models.deletion
import mail_extractor.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ImapServer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=20, verbose_name="Наименование imap сервера"
                    ),
                ),
            ],
            options={
                "verbose_name": "IMAP Сервер",
                "verbose_name_plural": "IMAP Сервера",
            },
        ),
        migrations.CreateModel(
            name="Mail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "login",
                    models.EmailField(max_length=254, verbose_name="Электронная почта"),
                ),
                (
                    "password",
                    models.CharField(
                        max_length=20,
                        verbose_name="Пароль для доступа по протоколу IMAP",
                    ),
                ),
                (
                    "server",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="mail_extractor.imapserver",
                        verbose_name="сервер IMAP",
                    ),
                ),
            ],
            options={
                "verbose_name": "Электронная почта",
                "verbose_name_plural": "Электронные почты",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Тема сообщения")),
                ("date_send", models.DateTimeField(verbose_name="Дата отправки")),
                ("date_receiving", models.DateTimeField(verbose_name="Дата получения")),
                ("text_message", models.TextField(verbose_name="текст сообщения")),
                (
                    "mail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mail_extractor.mail",
                        verbose_name="Эл.почта",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
        migrations.CreateModel(
            name="FileMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        unique=True,
                        upload_to=mail_extractor.models.upload_to_file,
                        verbose_name="Файл",
                    ),
                ),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="files",
                        to="mail_extractor.message",
                        verbose_name="Сообщение",
                    ),
                ),
            ],
            options={
                "verbose_name": "Файл",
                "verbose_name_plural": "Файлы",
            },
        ),
    ]
